### ISSUE TITLE
Map only works for Celle

### ISSUE THREAD

**Issue by tebsu** [tebsu/SRU#4]
Map only works for Celle (http://a3.sru-gaming.de/map.php)
Also resetting user query is wrong (BountyChiller 2 times due query not considering map_FK i guess) - and resetting doesnt work (Try Alphawolf)

**Comment by Spackenbremse** [comment]
Fixed mission_FK issue as well as not working reset (same source of issue).
Upcoming: reworking map-script to display other maps (Altis, Stratis etc.) as well.

**Comment by Spackenbremse** [comment]
fixed.
